define(["app",
    "ctrl/proposal/select_user_ctrl",
    "ctrl/proposal/proposal_list_ctrl",
    "ctrl/proposal/my_list_ctrl",
    "ctrl/proposal/wait_process_ctrl",
    "ctrl/proposal/processed_ctrl",
    "ctrl/proposal/add_ctrl",
    "ctrl/proposal/edit_ctrl",
    "ctrl/proposal/details_ctrl",
    "ctrl/proposal/details_process_ctrl",
    "ctrl/proposal/proposal_module_ctrl"
    ],function(huadeeapp){
    console.log('proposal_ctrl');
});