define(["app"],function(myapp){
    myapp.directive("ideasearchinput",[function(){
        return{
           scope:{
               data:'=',//输入框的默认参数
               inputmethods:"&",//事件
               subdata:'='
           },
            transclude:true,
            templateUrl:"js/directives/search_input/search_input.html",
            link:function(s,el,attrs){
                s.submitData={
                    input:[],//类型一
                    select:[],//类型二
                    single_select:[],//类型三
                    single_name:[],//类型四
                };
                //定义一个对象接受参数
                s.subMethData=function(){
                    s.subdata=s.submitData;
                    console.log(s.subdata,"++++++++++++++++s.submitData;s.submitData;+++++++++++++");
                };
            }
        };
    }]);
});
